sudo: true
language: generic

git:
  depth: 5

cache:
  directories:
  - "$HOME/.cabal"
  - "$HOME/.ghc"
  - "$HOME/.stack"
  - ".stack-work"

matrix:

  include:

  - ghc: 8.0.2
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack-8.0.2.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.2.2
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack-8.2.2.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.4.1
    env: STACK_YAML="$HOME/build/serokell/o-clock/stack.yaml"
    os: linux
    addons:
      apt:
        packages:
        - libgmp-dev

  - ghc: 8.4.1
    env: GHCVER='8.4.1' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-8.4.1
        - cabal-install-head

install:
  - |
    if [ -z "$STACK_YAML" ]; then
      export PATH="/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH"
      echo $PATH
      cp cabal.project.local.ubuntu-example cabal.project.local
      cabal new-update
      cabal new-build --enable-tests --enable-benchmarks --allow-newer -f aeson -f hashable -f serialise -f deepseq
    else
      mkdir -p ~/.local/bin
      export PATH="$HOME/.local/bin:$PATH"
      travis_retry curl -L 'https://www.stackage.org/stack/linux-x86_64' | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack --version
      stack setup --no-terminal
      stack setup --no-terminal --upgrade-cabal
      stack ghc -- --version
      stack build --only-dependencies --no-terminal --flag o-clock:aeson --flag o-clock:hashable --flag o-clock:serialise --flag o-clock:deepseq
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      cabal new-test --allow-newer
    else
      stack build --test --bench --no-terminal --flag o-clock:aeson --flag o-clock:hashable --flag o-clock:serialise --flag o-clock:deepseq
    fi

notifications:
  email: false
  slack:
    rooms:
      - serokell:T7L0cju5Nrn6ZkqWJCwNuOh4
    on_success: change
    on_failure: always
